version: '3.9'

services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - db

  web:
    image: nginx:stable-alpine
    container_name: laravel_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: laravel_db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - laravel_network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data:
